name: aave_liquidator
description: A Liquidator bot that monitor aave for liquidation opportunities.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies: 
  dotenv: ^3.0.0
  http: ^0.13.3 #used to make http request.
  web_socket_channel: ^2.1.0 # used to communicated with the network.
  web3dart: ^2.3.1 # for interacting with web3
  path: ^1.8.0 # A comprehensive, cross-platform path manipulation library for Dart.
  logger: ^1.1.0
  mongo_dart: ^0.7.3
  

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.4
